name: Deploy 1group.media to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/1025555791022/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'firebase-adminsdk-fbsvc@admin-1group.iam.gserviceaccount.com'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project admin-1group
